### ISSUE TITLE
Nodes not detected in the rectangles of the second level of this particular image

### ISSUE THREAD

**Issue by sakshamgupta1074** [yxdragon/sknw#14]
Input Image-
![colored_black](https://user-images.githubusercontent.com/39915573/103932954-a0ab2d00-5148-11eb-8c3d-f0ac05a1332e.jpg)

Output Image-
![knw_output](https://user-images.githubusercontent.com/39915573/103932997-b0c30c80-5148-11eb-95a6-18ff71a1c691.png)

**Comment by shiva2410** [comment]
Hello, I am facing the same issue mentioned above. Nodes are not created in the rectangles of the second level. 
I am trying to get a graph out of this image please suggest to me how to do it.

**Comment by yxdragon** [comment]
Hi, node in skeleton image means one pixel has more than 2 neighbours. So In your case, you should use binary_erosion and label to define every block, then trace the path (like sknw do, but you need write it yourself)
![image](https://user-images.githubusercontent.com/24822467/103983893-16eb7600-51c1-11eb-8ffa-dc60ba545b19.png)

another trick with sknw is do a binary_outline, then use sknw to build graph. 
![image](https://user-images.githubusercontent.com/24822467/104008851-01884300-51e5-11eb-8aaf-2ec7c3c6b0af.png)
and when two node has two path conected eachother, the two node means one!

**Comment by sakshamgupta1074** [comment]
Hello, thanks for the quick response. I am still not able to get the desired output even after creating the binary outline of the image. Also, your image is not visible on the comment for the another trick. Can you please elaborate the process?

**Comment by yxdragon** [comment]
hi, reload it again

**Comment by yxdragon** [comment]
hi, reload it again, and you can try imagepy, binary filter and sknw graph is built-in
![image](https://user-images.githubusercontent.com/24822467/104009074-6774ca80-51e5-11eb-80e1-03c0d4da0d15.png)

**Comment by sakshamgupta1074** [comment]
Thanks a lot, finally got the desired output!!
