### ISSUE TITLE
Does it matter if the skeleton is black or white? Skeletonize may expect white shapes and not black

### ISSUE THREAD

**Issue by aegonwolf** [yxdragon/sknw#20]
Hi, your sknw library works wonderfully, thanks.
I've come across an oddity you might want to know about.

When I have a binary mask, say some lines indicated as white, it works, but when I invert as in your documentation it doesn't work anymore. 
It looks like the thinning is done on white pixel areas:
https://scikit-image.org/docs/dev/auto_examples/edges/plot_skeleton.html

**Comment by yxdragon** [comment]
sknw treat 0 as background and other as foreground.
but what does 'doesn't works' mean? raise an error? or give wrong result?
