### ISSUE TITLE
Thank you for the package.

### ISSUE THREAD

**Issue by antran89** [yxdragon/sknw#8]
Thank for the useful package.

Could you please update the README and the test file? The following line is not true anymore in the new networkx, it could be better to give users a warning about it:

```
node, nodes = graph.node, graph.nodes()
```

**Comment by yxdragon** [comment]
Thanks for @charlesnchr 's pr, is It ok now?

**Comment by charlesnchr** [comment]
Yes, this has indeed been fixed now!

**Comment by antran89** [comment]
Yes, I checked the README, it is okay now!
